#Introducing NumPy

In [14]:
import numpy as np

In [15]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [16]:
arr1.shape

(5,)

In [17]:
type(arr1)

numpy.ndarray

In [18]:
for c in arr1:
    print(c)

1
2
3
4
5


In [19]:
items = np.array([[1,2,3], [4,5,6]])
print(items)

[[1 2 3]
 [4 5 6]]


In [20]:
print(type(items))

<class 'numpy.ndarray'>


In [21]:
matrix = np.matrix(items)
print(type(matrix))

<class 'numpy.matrix'>


In [23]:
matrix[1,1]

5